# Generated by Django 6.0.5 on 2026-05-15 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='movie/cinemas/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'], message='Faqatgina mp4, mov, avi formatlariga ruxsat berilgan!')])),
                ('annotation', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
