# Generated by Django 6.0.5 on 2026-05-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors/')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='actors',
            field=models.ManyToManyField(to='movie.actor'),
        ),
    ]
