# Generated by Django 6.0.5 on 2026-05-18 09:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_actor_cinema_actors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['-full_name'], 'verbose_name': 'Aktor', 'verbose_name_plural': 'Aktorlar'},
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Kino', 'verbose_name_plural': 'Kinolar'},
        ),
        migrations.AlterField(
            model_name='cinema',
            name='actors',
            field=models.ManyToManyField(to='movie.actor', verbose_name='Aktorlar'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qachon qo'shilgani"),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie/images/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='published_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Taqdim etilgan yili'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movie/cinemas/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'], message='Faqatgina mp4, mov, avi formatlariga ruxsat berilgan!')], verbose_name='Video'),
        ),
        migrations.CreateModel(
            name='CinemaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.cinema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
